---
global: include('global', required=False)

image: include('image', required=False)

app: include('app', required=True)

defaults: include('defaults', required=False)

jobs: list(include('job'), required=False)
---
global:
  image: include('image', required=False)
  imagePullSecrets: list(str(), required=False)
---
image:
  repository: str(required=False)
  tag: str(required=False)
  pullPolicy: str(required=False)
---
app:
  team: str(required=True)
  logs: include('logs', required=False)
---
logs:
  json: bool(required=False)
---
defaults:
  failedJobsHistoryLimit: int()
  successfulJobsHistoryLimit: int()
  concurrencyPolicy: enum('Allow', 'Forbid')
  resources: include('resources')
---
job:
  name: str(required=False)
  schedule: str(required=True)
  command: include('command', required=False)
  resources: include('resources', required=True)
  activeDeadlineSeconds: int(required=False)
  backoffLimit: int(required=False)
  env: list(include('env'), required=False)
---
command: list(str())
---
resources:
  enabled: bool(required=False)
  cpu: any(str(), int(), required=False)
  memory: str(required=False)
---
env:
  name: str(required=True)
  value: str(required=False)
  valueFrom: include('valueFrom', required=False)
---
valueFrom: map(str(), map(str(), str()))
