apiVersion: v1
kind: Service
metadata:
  name: {{ include "wapi-pcidss-v0.fullname" . }}
  labels:
    {{- include "wapi-pcidss-v0.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: api
  selector:
    {{- include "wapi-pcidss-v0.selectorLabels" . | nindent 4 }} 
