replicaCount: 1

initializationTask:
  create: true

metrics:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: prometheus

resources:
  requests:
    cpu: 100m
    memory: 256Mi
