apiVersion: v1
kind: Service
metadata:
  name: {{ include "hooker.fullname" . }}
  labels:
    {{- include "hooker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8022
      protocol: TCP
      name: http
  selector:
    {{- include "hooker.selectorLabels" . | nindent 4 }}
