apiVersion: v1
kind: Service
metadata:
  name: {{ include "hooker.fullname" . }}
  labels:
    {{- include "hooker.labels" . | nindent 4 }}
    {{- include .Values.podLabels . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.ports.management }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "hooker.selectorLabels" . | nindent 4 }}
