---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capi-pcidss-v1.fullname" . }}
type: Opaque
data:
  token_encryption_key1.jwk: {{ .Values.tokenEncryptionKey1 | b64enc | quote }}
  capi.privkey.pem: {{ .Values.capiPrivkey | b64enc | quote }}
