---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dominant.fullname" . }}
  labels:
    {{- include "dominant.labels" . | nindent 4 }}
data:
  sys.config: |
    {{- .Values.appConfig | nindent 4 }}
  vm.args: |
    -sname {{ include "dominant.fullname" . }}
    -setcookie {{ include "dominant.fullname" . }}_cookie
  erl_inetrc: |
    {{- .Values.vmConfig | nindent 4 }}
