{{- if .Values.inializationTask.create -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-initalization-task"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
        - name: dominant-init-job
          image: "{{ .Values.inializationTask.repository }}:{{ .Values.inializationTask.tag }}"
          command: ["{{ .Values.inializationTask.workdir }}/init-script"]
          volumeMounts:
            - name: config-volume
              mountPath: "{{ .Values.inializationTask.workdir }}/init-script"
              subPath: init-script
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: "{{ include "dominant.fullname" . }}-init-task"
            items:
              - key: init-script
                path: init-script
                mode: 0755
{{- end -}}
