server:
  dev:
    enabled: false
  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
  volumes:
    - name: vault-init
      configMap:
        name: vault-cm
        defaultMode: 0775
 # volumeMounts is a list of volumeMounts for the main server container. These are rendered
 # via toYaml rather than pre-processed like the extraVolumes value.
 # The purpose is to make it easy to share volumes between containers.
  volumeMounts:
    - mountPath: /vault-init
      name: vault-init

  dataStorage:
    enabled: true
    # Size of the PVC created
    size: 10Gi
    # Location where the PVC will be mounted.
    mountPath: "/vault/data"
    # Name of the storage class to use.  If null it will use the
    # configured default Storage Class.
    storageClass: null
    # Access Mode of the storage device being used for the PVC
    accessMode: ReadWriteOnce
    # Annotations to apply to the PVC
    annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
