cilium:
  enabled: false
elk:
  enabled: false
prometheus:
  enabled: false
ingress:
  enabled: true
  ip: 'someip'

services:
  global:
    ipv6only: false
  
  vault:
    dev: true

  ingress:
    class: "nginx"
    rootDomain: some-site.ru
    tls:
      enabled: true
      letsEncrypt:
        enabled: false
        issuer: ""
      secretName: someTlsSecret

