cilium:
  enabled: false
elk:
  enabled: true
prometheus:
  enabled: true

services:
  global:
    ipv6only: false
  
  vault:
    dev: true

  keycloak:
    externalUrl: "https://auth.some-site.com"

  ingress:
    rootDomain: cluster.yaclo-rbk.site
    tls:
      enabled: true
      secretName: yaoblako

