cilium:
  enabled: false
elk:
  enabled: false
prometheus:
  enabled: false

services:
  global:
    ipv6only: false
  
  vault:
    dev: true

  keycloak:
    externalUrl: "https://auth.some-site.com"

  ingress:
    class: "nginx"
    rootDomain: some-site.ru
    tls:
      enabled: true
      letsEncrypt:
        enabled: false
        issuer: ""
      secretName: someTlsSecret

