cilium:
  enabled: false
elk:
  enabled: false

services:
  global:
    ipv6only: true
  
  vault:
    dev: true

  keycloak:
    externalUrl: "https://auth.some-site.com"

  ingress:
    rootDomain: some-site.com
    tls: []
      # enabled: true
      # secretName: some-site-tls-cert

