cilium:
  enabled: false
elk:
  enabled: false
prometheus:
  enabled: false
ingress:
  enabled: false
  ip: 'someip'
certmanager:
  enabled: false

services:
  global:
    ipv6only: false
  
  vault:
    dev: true

  ingress:
    class: "nginx"
    rootDomain: some-site.ru
    insertNamespaceBeforeRootDomain: true
    tls:
      enabled: true
      letsEncrypt:
        enabled: true
        issuer: ""
      secretName: sometlssecret

