{{ readFile "hf-templates.yaml" }}

repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus
  <<: *default
  chart: prometheus-community/kube-prometheus-stack
  version: 10.1.0
  namespace: monitoring
- name: logs
  installed: true
  <<: *default
  chart: ./services/elk
