repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com

templates:
  default: &default
    chart: ./services/{{`{{ .Release.Name }}`}}
    namespace: default
    # This prevents helmfile exiting when it encounters a missing file
    # Valid values are "Error", "Warn", "Info", "Debug". The default is "Error"
    # Use "Debug" to make missing files errors invisible at the default log level(--log-level=INFO)
    missingFileHandler: Warn
    values:
    - config/{{`{{ .Release.Name }}`}}/values.yaml

releases:
- name: zookeeper
  <<: *default
  chart: incubator/zookeeper
  version: 2.1.3
- name: kafka
  <<: *default
  chart: incubator/kafka
  version: 0.21.2
- name: consul
  <<: *default
  chart: stable/consul
  version: 3.9.5
- name: mg-riak
  <<: *default
  chart: ./services/riak
  set:
  - name: config.user
    file: config/mg-riak/user.yaml
- name: machinegun
  <<: *default
  set:
  - name: appConfig
    file: config/machinegun/config.yaml
- name: kds
  <<: *default
  set:
  - name: appConfig
    file: config/kds/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
  - name: caCrt
    file: config/kds/ca.crt
  - name: serverCrt
    file: config/kds/server.pem
  - name: keyring
    file: config/kds/keyring
- name: cds
  <<: *default
  set:
  - name: appConfig
    file: config/cds/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
  - name: caCrt
    file: config/cds/ca.crt
  - name: clientCrt
    file: config/cds/client.pem
- name: url-shortener
  <<: *default
  set:
  - name: appConfig
    file: config/url-shortener/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
- name: binbase
  <<: *default
  set:
  - name: entrypoint
    file: config/binbase/entrypoint.sh
- name: capi-v2
  <<: *default
  set:
  - name: ingressHost
    value: api.rbk.dev
  - name: ingressPath
    value: /v2
  - name: fetchKeycloakPubkey
    file: config/api-common/fetch-keycloak-pubkey.sh
  - name: appConfig
    file: config/capi-v2/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
  - name: oopsBody1
    file: config/capi-v2/oops-bodies/sad-kitty1
  - name: oopsBody2
    file: config/capi-v2/oops-bodies/sad-kitty2
  - name: tokenEnctyptionKey1
    file: config/capi-v2/keys/token-encryption-keys/1.jwk
  - name: capiPrivkey
    file: config/capi-v2/keys/capi.privkey.pem
