{{ readFile "hf-templates.yaml" }}

repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: cilium
  url: https://helm.cilium.io/

releases:
- name: prometheus
  <<: *default
  chart: prometheus-community/kube-prometheus-stack
  version: 10.1.0
  namespace: monitoring
- name: logs
  # Change to installed: true if you need ECK installed
  installed: true
  <<: *default
  chart: ./services/elk
- name: cilium
  <<: *default
  version: 1.8.5
  chart: cilium/cilium
  namespace: kube-system
