bases:
  - environments.yaml
---

{{ readFile "hf-templates.yaml" }}

repositories:
- name: rbkmoney
  url: https://rbkmoney.github.io/charts
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: certmanager
  url: https://charts.jetstack.io

releases:
- name: ingress
  installed: {{ .Values.ingress.enabled }}
  <<: *infra_default
  chart: ingress-nginx/ingress-nginx
{{- if eq .Values.elk.enabled true }}
- name: logs
  <<: *infra_default
  chart: rbkmoney/elk
{{- end }}
- name: netpolicy
  installed: {{ .Values.cilium.enabled }}
  <<: *infra_default
  chart: rbkmoney/netpolicy
{{- if eq .Values.certmanager.enabled true }}
- name: certmanager
  <<: *infra_default
  namespace: cert-manager
  chart: certmanager/cert-manager
{{- end }}
