{{ readFile "hf-templates.yaml" }}

repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: incubator
  url: https://charts.helm.sh/incubator
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: hashicorp
  url: https://helm.releases.hashicorp.com
- name: codecentric
  url: https://codecentric.github.io/helm-charts

#helmfiles:
#- # Path to the helmfile state file being processed BEFORE releases in this state file
#  path: helmfile-infra.yaml

releases:
- name: zookeeper
  <<: *default
  chart: incubator/zookeeper
  version: 2.1.3
- name: kafka
  <<: *default
  needs:
  - default/zookeeper
  chart: incubator/kafka
  version: 0.21.2
- name: consul
  <<: *default
  chart: stable/consul
  version: 3.9.5
- name: postgres
  <<: *default
  chart: bitnami/postgresql
  version: 9.2.0
  wait: true
- name: vault
  <<: *default
  chart: hashicorp/vault
  version: 0.7.0
  needs:
  - default/postgres
  wait: true
- name: keycloak-realms
  <<: *default
- name: keycloak
  <<: *default
  chart: codecentric/keycloak
  version: 9.0.1
  needs:
  - default/postgres
  wait: true
- name: holmes
  <<: *default
- name: riak
  <<: *default
  labels:
    logfmt: json
  chart: ./services/riak
  set:
  - name: config.user
    file: config/riak/user.yaml
- name: machinegun
  <<: *default
  labels:
    logfmt: json
  needs:
  - default/consul
  - default/riak
  - default/kafka
- name: bender
  <<: *default
  labels:
    logfmt: json
- name: kds
  <<: *default
  labels:
    logfmt: json
- name: cds
  <<: *default
  labels:
    logfmt: json
  needs:
    - default/kds
    - default/riak
- name: shumway
  <<: *default
  labels:
    logfmt: json
  needs:
  - default/vault
  - default/postgres
  wait: true
- name: hooker
  <<: *default
  needs:
  - default/vault
  - default/kafka
- name: dominant
  <<: *default
  labels:
    logfmt: json
  needs:
  - default/shumway
  wait: true
- name: binbase
  <<: *default
- name: proxy-mocketbank
  <<: *default
  labels:
    logfmt: json
  needs:
    - default/hellgate
- name: proxy-mocketbank-mpi
  <<: *default
  labels:
    logfmt: json
  needs:
    - default/proxy-mocketbank
- name: proxy-mocket-inspector
  <<: *default
  labels:
    logfmt: json
  needs:
    - default/hellgate
- name: hellgate
  <<: *default
  labels:
    logfmt: json
  needs:
    - default/dominant
- name: capi-pcidss-v2
  <<: *default
  labels:
    logfmt: json
  #needs:
  #  - default/keycloak
- name: capi-pcidss-v1
  <<: *default
  chart: ./generic_charts/stateless/
  labels:
    logfmt: json
  #needs:
  #  - default/keycloak
- name: url-shortener
  <<: *default
- name: capi-v1
  <<: *default
  labels:
    logfmt: json
  needs:
    - default/keycloak
- name: capi-v2
  <<: *default
  labels:
    logfmt: json
  needs:
    - default/keycloak
- name: wapi-pcidss-v0
  installed: false
  <<: *default
  labels:
    logfmt: json
  needs:
    - default/keycloak
- name: wapi
  installed: false
  <<: *default
  labels:
    logfmt: json
  needs:
    - default/keycloak
- name: payform
  <<: *default
  set:
  - name: appconfig
    file: config/payform/appConfig.json
- name: test-transaction
  <<: *default
  needs:
    - default/shumway
    - default/dominant
    - default/cds
    - default/keycloak
