{{ readFile "hf-templates.yaml" }}

repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: incubator
  url: https://charts.helm.sh/incubator
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: hashicorp
  url: https://helm.releases.hashicorp.com
- name: codecentric
  url: https://codecentric.github.io/helm-charts
- name: rbkmoney
  url: https://rbkmoney.github.io/charts

# Path to the helmfile state file being processed BEFORE releases in this state file
helmfiles:
-  path: helmfile-infra.yaml

releases:
#External releases
- name: kafka
  <<: *default
  chart: incubator/kafka
  version: 0.21.2
- name: consul
  <<: *default
  chart: stable/consul
  version: 3.9.5
- name: postgres
  <<: *default
  chart: bitnami/postgresql
  version: 9.2.0
  wait: true
- name: vault
  <<: *default
  chart: hashicorp/vault
  version: 0.7.0
  needs:
  - default/postgres
  wait: true
- name: keycloak-realms
  <<: *default
- name: keycloak
  <<: *default
  chart: codecentric/keycloak
  version: 9.0.1
  needs:
  - default/postgres
  wait: true
#Rbkmoney processing releases
- name: holmes
  <<: *generic_stateless
- name: riak
  <<: *generic_statefull_json
- name: machinegun
  <<: *generic_stateless_json
  needs:
  - default/consul
  - default/riak
  - default/kafka
- name: bender
  <<: *generic_statefull_json
- name: kds
  <<: *generic_stateless_json
- name: cds
  <<: *generic_stateless_json
  needs:
    - default/kds
    - default/riak
- name: shumway
  <<: *generic_stateless_json
  needs:
  - default/vault
  - default/postgres
  wait: true
- name: hooker
  <<: *generic_stateless
  needs:
  - default/vault
  - default/kafka
- name: dominant
  <<: *generic_stateless_json
  needs:
  - default/shumway
  wait: true
- name: binbase
  <<: *generic_stateless
- name: proxy-mocketbank
  <<: *generic_stateless_json
  needs:
    - default/hellgate
- name: proxy-mocketbank-mpi
  <<: *generic_stateless_json
  needs:
    - default/proxy-mocketbank
- name: proxy-mocket-inspector
  <<: *generic_stateless_json
  needs:
    - default/hellgate
- name: hellgate
  <<: *generic_stateless_json
  needs:
    - default/dominant
- name: capi-pcidss-v2
  <<: *generic_stateless_json
  needs:
    - default/keycloak
- name: capi-pcidss-v1
  <<: *generic_stateless_json
  needs:
    - default/keycloak
- name: url-shortener
  <<: *generic_stateless
- name: capi-v1
  <<: *generic_stateless_json
  needs:
    - default/keycloak
- name: capi-v2
  <<: *generic_stateless_json
  needs:
    - default/keycloak
- name: wapi-pcidss-v0
  installed: false
  <<: *generic_stateless_json
  needs:
   - default/keycloak
- name: wapi
  installed: false
  <<: *generic_stateless_json
  needs:
    - default/keycloak
- name: payform
  <<: *generic_stateless
- name: test-transaction
  <<: *default
  chart: rbkmoney/test-transaction
  needs:
    - default/shumway
    - default/dominant
    - default/cds
    - default/keycloak
- name: anapi
  <<: *generic_stateless_json
  needs:
    - default/keycloak
