repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: hashicorp
  url: https://helm.releases.hashicorp.com

templates:
  default: &default
    chart: ./services/{{`{{ .Release.Name }}`}}
    namespace: default
    # This prevents helmfile exiting when it encounters a missing file
    # Valid values are "Error", "Warn", "Info", "Debug". The default is "Error"
    # Use "Debug" to make missing files errors invisible at the default log level(--log-level=INFO)
    missingFileHandler: Warn
    values:
    - config/{{`{{ .Release.Name }}`}}/values.yaml

releases:
- name: zookeeper
  <<: *default
  chart: incubator/zookeeper
  version: 2.1.3
- name: kafka
  <<: *default
  chart: incubator/kafka
  version: 0.21.2
- name: consul
  <<: *default
  chart: stable/consul
  version: 3.9.5
- name: postgres
  <<: *default
  chart: bitnami/postgresql
  version: 9.2.0
- name: mg-riak
  <<: *default
  chart: ./services/riak
  set:
  - name: config.user
    file: config/mg-riak/user.yaml
- name: machinegun
  <<: *default
  set:
  - name: appConfig
    file: config/machinegun/config.yaml
- name: kds
  <<: *default
  set:
  - name: appConfig
    file: config/kds/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
  - name: caCrt
    file: config/kds/ca.crt
  - name: serverCrt
    file: config/kds/server.pem
  - name: keyring
    file: config/kds/keyring
- name: bender
  <<: *default
  set:
  - name: appConfig
    file: config/bender/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
- name: cds
  <<: *default
  set:
  - name: appConfig
    file: config/cds/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
  - name: caCrt
    file: config/cds/ca.crt
  - name: clientCrt
    file: config/cds/client.pem
- name: capi-pcidss-v2
  <<: *default
  set:
  - name: fetchKeycloakPubkey
    file: config/api-common/fetch-keycloak-pubkey.sh
  - name: appConfig
    file: config/capi-pcidss-v2/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
  - name: privatePem
    file: config/api-common/keys/capi.privkey.pem
  - name: tokenEnctyptionKey1
    file: config/api-common/keys/token-encryption-keys/1.jwk
- name: url-shortener
  <<: *default
  set:
  - name: appConfig
    file: config/url-shortener/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
- name: binbase
  <<: *default
  set:
  - name: entrypoint
    file: config/binbase/entrypoint.sh
- name: dominant
  <<: *default
  set:
  - name: initializationTask.script
    file: config/dominant/init-script.sh
  - name: appConfig
    file: config/dominant/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
- name: hellgate
  <<: *default
  set:
  - name: appConfig
    file: config/hellgate/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
- name: capi-v1
  <<: *default
  set:
  - name: fetchKeycloakPubkey
    file: config/api-common/fetch-keycloak-pubkey.sh
  - name: appConfig
    file: config/capi-v1/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
  - name: oopsBody1
    file: config/api-common/oops-bodies/sad-kitty1
  - name: oopsBody2
    file: config/api-common/oops-bodies/sad-kitty2
  - name: tokenEnctyptionKey1
    file: config/api-common/keys/token-encryption-keys/1.jwk
  - name: capiPrivkey
    file: config/api-common/keys/capi.privkey.pem
- name: capi-v2
  <<: *default
  set:
  - name: fetchKeycloakPubkey
    file: config/api-common/fetch-keycloak-pubkey.sh
  - name: appConfig
    file: config/capi-v2/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
  - name: oopsBody1
    file: config/api-common/oops-bodies/sad-kitty1
  - name: oopsBody2
    file: config/api-common/oops-bodies/sad-kitty2
  - name: tokenEnctyptionKey1
    file: config/api-common/keys/token-encryption-keys/1.jwk
  - name: capiPrivkey
    file: config/api-common/keys/capi.privkey.pem
- name: wapi-pcidss-v0
  <<: *default
  set:
  - name: fetchKeycloakPubkey
    file: config/api-common/fetch-keycloak-pubkey.sh
  - name: appConfig
    file: config/wapi-pcidss-v0/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
  - name: privatePem
    file: config/api-common/keys/capi.privkey.pem
  - name: tokenEnctyptionKey1
    file: config/api-common/keys/token-encryption-keys/1.jwk
- name: vault
  <<: *default
  chart: hashicorp/vault
  version: 0.7.0
- name: wapi
  <<: *default
  set:
  - name: fetchKeycloakPubkey
    file: config/api-common/fetch-keycloak-pubkey.sh
  - name: appConfig
    file: config/wapi/sys.config
  - name: vmConfig
    file: config/vm/erl_inetrc
  - name: oopsBody1
    file: config/api-common/oops-bodies/sad-kitty1
  - name: oopsBody2
    file: config/api-common/oops-bodies/sad-kitty2
  - name: tokenEnctyptionKey1
    file: config/api-common/keys/token-encryption-keys/1.jwk
  - name: wapiPrivkey
    file: config/api-common/keys/capi.privkey.pem
- name: proxy-mocketbank
  <<: *default
  set:
  - name: knownCards
    file: config/proxy-mocketbank/cards.csv
  - name: errorMapping
    file: config/proxy-mocketbank/errors.json
- name: prometheus
  <<: *default
  chart: stable/prometheus-operator
  namespace: monitoring
  createNamespace: true
- name: shumway
  <<: *default
  set:
  - name: entrypoint
    file: config/shumway/entrypoint.sh
- name: hooker
  <<: *default
  set:
  - name: entrypoint
    file: config/hooker/entrypoint.sh
