bases:
  - environments.yaml
---

{{ readFile "hf-templates.yaml" }}

repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: rbkmoney
  url: https://rbkmoney.github.io/charts

releases:
- name: prometheus
  <<: *infra_default
  chart: prometheus-community/kube-prometheus-stack
  version: 12.1.0
  namespace: monitoring
  needs:
    - monitoring/logs
- name: logs
  installed: {{ .Values.elk.enabled }}
  <<: *infra_default
  namespace: monitoring
  chart: rbkmoney/elk
- name: netpolicy
  installed: {{ .Values.cilium.enabled }}
  <<: *infra_default
  chart: rbkmoney/netpolicy
