{{ readFile "hf-templates.yaml" }}

repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
  #- name: grafana
  #  url: https://grafana.github.io/helm-charts

releases:
- name: prometheus
  <<: *default
  chart: prometheus-community/kube-prometheus-stack
  version: 10.1.0
  namespace: monitoring
  needs:
  - monitoring/logs
#  - default/logs
- name: logs
  # Change to installed: true if you need ECK installed
  installed: true
  <<: *default
  namespace: monitoring
  chart: ./services/elk
  #- name: grafana
  #  <<: *default
  #  chart: grafana/grafana
  #  version: 6.1.3
