apiVersion: v1
kind: Service
metadata:
  name: {{ include "magista-kafka.fullname" . }}
  labels:
    {{- include "magista-kafka.labels" . | nindent 4 }}
  {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.ports.management }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "magista-kafka.selectorLabels" . | nindent 4 }}
