apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hellgate.fullname" . }}
  labels:
    {{- include "hellgate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hellgate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        hellgate/properties-hash: {{ include "hellgate.propertiesHash" . }}
      labels:
        {{- include "hellgate.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hellgate.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: 8022
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: api
          readinessProbe:
            httpGet:
              path: /health
              port: api
          volumeMounts:
            - name: config-volume
              mountPath: /opt/hellgate/releases/0.1/sys.config
              subPath: sys.config
              readOnly: true
            - name: config-volume
              mountPath: /opt/hellgate/releases/0.1/vm.args
              subPath: vm.args
              readOnly: true
            - name: config-volume
              mountPath: /opt/hellgate/erl_inetrc
              subPath: erl_inetrc
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "hellgate.fullname" . }}
            items:
            - key: sys.config
              path: sys.config
            - key: vm.args
              path: vm.args
            - key: erl_inetrc
              path: erl_inetrc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
