apiVersion: v1
kind: Service
metadata:
  name: {{ include "wapi.fullname" . }}
  labels:
    {{- include "wapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
    - port: {{ .Values.service.ports.ingressPort }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "wapi.selectorLabels" . | nindent 4 }}
