# Look for reference at https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2008
prometheus:
  additionalServiceMonitors:
    - name: "rbk-erlang-service"
      selector:
        matchLabels:
          prometheus.metrics.erlang.enabled: "true"
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: "api"
          path: /metrics
          scheme: http
    - name: "rbk-java-service"
      selector:
        matchLabels:
          prometheus.metrics.java.enabled: "true"
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: "management"
          path: /actuator/prometheus
          scheme: http

grafana:
  enabled: true

  admin:
    existingSecret: rbkmoney-grafana-admin-user
    userKey: admin-user
    passwordKey: admin-password

  envValueFrom:
    CH_PASSWORD:
      secretKeyRef:
        name: rbkmoney-clickhouse-readonly-user
        key: password
    CH_USERNAME:
      secretKeyRef:
        name: rbkmoney-clickhouse-readonly-user
        key: username

  env:
    GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: vertamedia-clickhouse-datasource

  plugins:
    - vertamedia-clickhouse-datasource
    - grafana-piechart-panel

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: standoff-clickhouse
          type: vertamedia-clickhouse-datasource
          access: proxy
          url: http://clickhouse.default.svc.cluster.local:8123

          # <bool> enable/disable basic auth
          basicAuth: true
          # <string> basic auth username
          basicAuthUser: $CH_USERNAME
          # <string> basic auth password
          basicAuthPassword: $CH_PASSWORD
          # <bool> enable/disable with credentials headers
          withCredentials: false
          # <bool> mark as default datasource. Max one per org
          isDefault: false
          # <map> fields that will be converted to json and stored in json_data
          jsonData:
              # <bool> enable/disable sending 'add_http_cors_header=1' parameter
              addCorsHeader: false
              # <bool> enable/disable using POST method for sending queries
              usePOST: false
              # <string> default database name
              defaultDatabase: fraud

  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: true

    ## Annotations for Grafana Ingress
    ##
    annotations:
      kubernetes.io/ingress.class: internal_waf
      # kubernetes.io/tls-acme: "true"

    ## Labels to be added to the Ingress
    ##
    labels: {}

    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    # hosts:
    #   - grafana.domain.com
    hosts:
      - grafana.rbkmoney.standoff.city
    path: /

    tls:
    - secretName: "stand-wild"
      hosts:
      - grafana.rbkmoney.standoff.city

  persistence:
    type: pvc
    enabled: true
    # storageClassName: default
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
