# Look for reference at https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2008
prometheus:
  additionalServiceMonitors:
    - name: "rbk-intservice"
      selector:
        matchLabels:
          prometheusmetrics.enabled: "true"
      namespaceSelector:
        matchNames:
        - default
      endpoints:
        - port: "api"
          path: /metrics
          scheme: http
