---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "riak.fullname" . }}
  labels:
    {{- include "riak.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "riak.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        riak/properties-hash: {{ include "riak.propertiesHash" . }}
      labels:
        app: {{ .Chart.Name }}
        {{- include "riak.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "riak.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLUSTER_NAME
              value: "riak"
            - name: COORDINATOR_NODE
              value: {{ include "riak.fullname" . }}-0.{{ include "riak.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            # - name: NODENAME
            #   value: ${HOSTNAME}.{{ .Chart.Name }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 8098
            - name: protobuf
              protocol: TCP
              containerPort: 8087
          livenessProbe:
            exec:
              command: ["riak", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 15
          readinessProbe:
            exec:
              command: ["riak-admin", "test"]
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
          volumeMounts:
            - name: config-volume
              mountPath: /etc/riak/user.conf
              subPath: user.conf
              readOnly: true
            - name: data
              mountPath: /var/lib/riak
      imagePullSecrets:
        - name: "{{ .Values.imagePullSecrets.name }}"
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "riak.fullname" . }}-user-config
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{ if .Values.state.need -}}
  volumeClaimTemplates:
    - metadata:
        name: data
    {{- with .Values.storage }}
      spec:
       {{- toYaml . | nindent 10 }}
    {{- end }}
  {{- end -}}
