---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "riak.fullname" . }}
  labels:
    {{- include "riak.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "riak.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        riak/properties-hash: {{ include "riak.propertiesHash" . }}
      labels:
        app: {{ .Chart.Name }}
        {{- include "riak.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "riak.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.podSecurityContext.fsGroup | int64 }}
        runAsUser: 0
        runAsGroup: {{ .Values.podSecurityContext.fsGroup | int64 }}      
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
           capabilities:
             add: 
             - "SYS_CHROOT"
             - "NET_RAW"
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLUSTER_NAME
              value: "riak"
            - name: COORDINATOR_NODE
              value: {{ include "riak.fullname" . }}-0.{{ include "riak.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
          ports:
            - name: http
              protocol: TCP
              containerPort: 8098
            - name: protobuf
              protocol: TCP
              containerPort: 8087
          livenessProbe:
            exec:
              command: ["riak", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 15
          readinessProbe:
            exec:
              command: ["riak-admin", "test"]
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
          volumeMounts:
            - name: config-volume
              mountPath: /etc/riak/user.conf
              subPath: user.conf
              readOnly: true
            - name: data
              mountPath: /var/lib/riak
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "riak.fullname" . }}-user-config
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      {{- with .Values.storage }}
      spec:
       {{- toYaml . | nindent 10 }}
      {{- end }}
