---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: default.consul
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      k8s:selector.cilium.rbkmoney/release: consul
  egress:
  - toEndpoints:
      - matchLabels:
          k8s:app.kubernetes.io/name: machinegun
