---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-kafka-zookeeper"
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/component: kafka-broker
  ingress:
    - fromEndpoints:
      - matchLabels:
          k8s:app: zookeeper
  egress:
    - toEndpoints:
      - matchLabels:
          k8s:app: zookeeper
      toPorts:
      - ports:
        - port: "2181"
          protocol: TCP
