---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-kafka-zookeeper"
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      k8s:app: zookeeper
      k8s:component: server
  ingress:
    - toPorts:
      - ports:
        - protocol: TCP
          port: "2181"
      fromEndpoints:
        - matchLabels:
            k8s:app.kubernetes.io/component: kafka-broker
            k8s:app.kubernetes.io/name: kafka
