---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: default.monitoring
  namespace: default
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
    - toPorts:
      - ports:
        - protocol: TCP
          port: "8022"
        - protocol: TCP
          port: "8080"
      fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
        - matchLabels:
            k8s:app: consul
    - toPorts:
      - ports:
        - protocol: TCP
          port: "8080"
        rules:
          http:
          - method: "GET"
            path: "/metrics"
      fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
            k8s:app: prometheus
