---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default.pgsql
  namespace: default
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - ports:
      - protocol: TCP
        port: 5123
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
        - namespaceSelector:
            matchLabels:
              namespace: kube-system
        - namespaceSelector:
            matchLabels:
              namespace: monitoring
