---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: default.kafka
  namespace: default
spec:
  endpointSelector:
    matchLabels: {}
  egress:
    - toPorts:
      - ports:
        - protocol: TCP
          port: "9092"
      toEndpoints:
        - matchLabels:
            k8s:app.kubernetes.io/name: kafka
