# Default values for machinegun.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dr2.rbkmoney.com/rbkmoney/machinegun
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# An Erlang distribution cookie.
cookie:
  path: "/opt/machinegun/etc/cookie"
  # value: "some-secret-value"

appConfig: |
  service_name: machinegun
  erlang:
    secret_cookie_file: "/opt/machinegun/etc/cookie"
  namespaces:
    mg_test_ns:
      processor:
          url: http://localhost:8022/processor
  storage:
    type: memory

# Specifies a script to generate application config.
# See https://github.com/rbkmoney/machinegun/blob/master/rel_scripts/configurator.escript.
# If not defined, choosing the default embedded script from the service image.
# appConfigurator: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8022

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
