---
global: include('global', required=False)

app: include('app', required=True)

replicaCount: int(min=1, required=False)

initContainers: list(include('initContainer'), required=False)

hooks: list(include('hook'), required=False)

service: include('service', required=False)

resources: include('resources', required=False)

linkerd: include('linkerd', required=False)

redis: include('redis', required=False)

azureRedis: include('azureRedis', required=False)

cronjobs: include('cronjobs', required=False)

ingresses: list(include('ingress'), required=False)

stunnel: include('stunnel', required=False)
---
global:
  image: include('image', required=False)
  imagePullSecrets: list(str(), required=False)
---
image:
  repository: str(required=False)
  tag: str(required=False)
  pullPolicy: str(required=False)
---
app:
  team: str(required=True)
  port: int(required=False)
  env: list(include('env'), required=False)
  metrics: include('metrics', required=False)
  logs: include('logs', required=False)
  probes: include('probes', required=False)
  additionalAnnotations: map(str(), str(), required=False)
---
env:
  name: str(required=True)
  value: str(required=False)
  valueFrom: include('valueFrom', required=False)
---
valueFrom: map(str(), map(str(), str()))
---
metrics:
  enabled: bool(required=False)
  path: str(required=False)
  interval: str(required=False)
---
logs:
  json: bool(required=False)
---
probes:
  livenessPath: str(required=False)
  readinessPath: str(required=False)
  initialDelaySeconds: int(min=0, required=False)
  periodSeconds: int(min=5, max=20, required=False)
  failureThreshold: int(min=1, max=5, required=False)
  timeoutSeconds: int(min=1, max=10, required=False)
---
initContainer:
  name: str(required=True)
  image: include('image', required=False)
  command: include('command')
  env: list(include('env'), required=False)
---
command: list(str())
---
hook:
  name: str(required=True)
  image: include('image', required=False)
  command: include('command', required=False)
  env: list(include('env'), required=False)
---
service:
  type: str(required=False)
  port: int(required=False)
---
redis:
  temp: bool(required=False)
  azure: bool(required=False)
---
resources:
  enabled: bool(required=False)
  cpu: any(str(), int(), required=False)
  memory: str(required=False)
---
linkerd:
  enabled: bool(required=False)
---
azureRedis:
  uri: str(required=False)
---
cronjobs:
  image: include('image', required=False)
  jobs: list(include('job'), required=False)
  app: include('cronjobsApp', required=False)
---
cronjobsApp:
  team: str(required=True)
---
job:
  name: str(required=False)
  schedule: str(required=True)
  command: include('command')
  resources: include('resources', required=False)
  activeDeadlineSeconds: int()
  env: list(include('env'), required=False)
---
ingress:
  host: str(required=True)
  name: str(required=False)
  ssl: enum('enabled', 'disabled', required=False)
  paths: list(str(), required=True)
  split: bool(required=False)
  canary: include('canary', required=False)
  additionalAnnotations: map(str(), str(), required=False)
---
canary:
  weight: int(min=0, max=100, required=False)
  cookie: str(required=False)
---
stunnel:
  image: include('image', required=False)
  imagePullSecrets: list(str(), required=False)
  replicaCount: int(min=1, required=False)
  port: int(required=False)
  service: include('service', required=False)
  resources: include('resources', required=False)
  tunnels: list(include('tunnel'), required=True)
---
tunnel:
  name: str(required=True)
  address: str(required=True)
  certificates: include('certificates', required=True)
---
certificates:
  ca: str(required=True)
  cert: str(required=False)
  key: str(required=False)
