ingress:
  host: api.rbkmoney.standoff.city
  path: /v1
replicaCount: 1

metrics:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: prometheus

resources:
  requests:
    cpu: 100m
    memory: 128Mi
