replicas: 1

zookeeper:
  ## If true, install the Zookeeper chart alongside Kafka
  ## ref: https://github.com/kubernetes/charts/tree/master/incubator/zookeeper
  enabled: false

  ## If the Zookeeper Chart is disabled a URL and port are required to connect
  url: "zookeeper"
  port: 2181
