---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stateless.fullname" . }}
  labels:
    {{- include "stateless.labels" . | nindent 4 }}
data:
  {{ toYaml .Values.configMap.data | nindent 2 }}
