{{- if .Values.cilium.enabled -}}
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: holmes-allow-all
  namespace: default
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: default
        k8s:app.kubernetes.io/name: holmes
{{- end -}}
