configMap:
  data:
    init.vault.sh: |
      sleep 2
      vault secrets enable database
      vault write database/config/shumway \
          plugin_name=postgresql-database-plugin \
          allowed_roles="*" \
          connection_url="postgresql://{{username}}:{{password}}@postgres-postgresql:5432/shumway?sslmode=disable" \
          username="postgres" \
          password="H@ckM3"
      vault write database/roles/db-app-shumway \
          db_name=shumway \
          creation_statements="CREATE SCHEMA IF NOT EXISTS shm;
          CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
          GRANT CREATE ON DATABASE shumway TO \"{{name}}\";
          GRANT ALL ON SCHEMA shm TO \"{{name}}\";
          GRANT ALL ON ALL TABLES IN SCHEMA shm TO \"{{name}}\";
          GRANT ALL ON ALL SEQUENCES IN SCHEMA shm TO \"{{name}}\";" \
          default_ttl="1h" \
          max_ttl="240h"
      vault write database/config/hooker \
          plugin_name=postgresql-database-plugin \
          allowed_roles="*" \
          connection_url="postgresql://{{username}}:{{password}}@postgres-postgresql:5432/hooker?sslmode=disable" \
          username="postgres" \
          password="H@ckM3"
      vault write database/roles/db-app-hooker \
          db_name=hooker \
          creation_statements="CREATE SCHEMA IF NOT EXISTS hook;
          CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
          GRANT CREATE ON DATABASE hooker TO \"{{name}}\";
          GRANT ALL ON SCHEMA hook TO \"{{name}}\";
          GRANT ALL ON ALL TABLES IN SCHEMA hook TO \"{{name}}\";
          GRANT ALL ON ALL SEQUENCES IN SCHEMA hook TO \"{{name}}\";" \
          default_ttl="1h" \
          max_ttl="240h"
      vault write database/config/fistful-reporter-kafka \
          plugin_name=postgresql-database-plugin \
          allowed_roles="*" \
          connection_url="postgresql://{{username}}:{{password}}@postgres-postgresql:5432/fistful-reporter-kafka?sslmode=disable" \
          username="postgres" \
          password="H@ckM3"
      vault write database/roles/db-app-fistful-reporter-kafka \
          db_name=fistful-reporter-kafka \
          creation_statements="CREATE SCHEMA IF NOT EXISTS fr;
          CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
          GRANT CREATE ON DATABASE fistful-reporter-kafka TO \"{{name}}\";
          GRANT ALL ON SCHEMA fr TO \"{{name}}\";
          GRANT ALL ON ALL TABLES IN SCHEMA fr TO \"{{name}}\";
          GRANT ALL ON ALL SEQUENCES IN SCHEMA fr TO \"{{name}}\";" \
          default_ttl="1h" \
          max_ttl="240h"

      vault auth enable kubernetes
      vault write auth/kubernetes/config \
             token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
             kubernetes_host=https://${KUBERNETES_PORT_443_TCP_ADDR}:443 \
             kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  
      vault write auth/kubernetes/role/db-app \
          bound_service_account_names="*" \
          bound_service_account_namespaces="*" \
          policies=db-app \
          ttl=1h
  
      vault policy write db-app /vault-init/db-policy.hcl
    db-policy.hcl: |
      path "database/creds/db-app-shumway" {
        capabilities = ["read"]
      }
      path "database/creds/db-app-hooker" {
        capabilities = ["read"]
      }
      path "database/creds/db-app-fistful-reporter-kafka" {
        capabilities = ["read"]
      }
