
postgresql:
    enabled: false

podAnnotations:
  vault.hashicorp.com/role: "db-app"
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-secret-dbuser: "database/creds/db-kk"
  vault.hashicorp.com/agent-inject-template-dbuser: |
    {{`{{- with secret "database/creds/db-kk" -}}
    {{ .Data.username }}
    {{- end }}`}}
  vault.hashicorp.com/agent-inject-secret-dbpass: "database/creds/db-kk"
  vault.hashicorp.com/agent-inject-template-dbpass: |
    {{`{{- with secret "database/creds/db-kk" -}}
    {{ .Data.password }}
    {{- end }}`}}


startupScripts:
  nenvget.sh: |
    echo $DB_USER_FILE $DB_PASSWORD_FILE

extraEnv: |
  - name: DB_VENDOR
    value: postgres
  - name: DB_ADDR
    value: postgres-postgresql
  - name: DB_PORT
    value: "5432"
  - name: DB_DATABASE
    value: keycloak
  - name: DB_USER_FILE
    value: /vault/secrets/dbuser
  - name: DB_PASSWORD_FILE
    value: /vault/secrets/dbpass
  - name: JAVA_OPTS
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.net.preferIPv4Stack=true
      -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
      -Djava.awt.headless=true
  - name: KEYCLOAK_IMPORT
    value: /realm/realms.json

extraVolumes: |
  - name: keycloak-realms-volume
    configMap:
      name: keycloak-realms

extraVolumeMounts: |
  - name: keycloak-realms-volume
    mountPath: "/realm/"
    readOnly: true

ingress:
  enabled: true
  rules:
    -
      host: 'auth.rbkmoney.standoff.city'
      paths: 
        - /
  tls:
    - hosts:
        - auth.rbkmoney.standoff.city
      secretName: "stand-wild"
