apiVersion: v1
kind: Service
metadata:
  name: {{ include "payform.fullname" . }}
  labels:
    {{- include "payform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: api
  selector:
    {{- include "payform.selectorLabels" . | nindent 4 }}
