---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-transaction.fullname" . }}
  labels:
    {{- include "test-transaction.labels" . | nindent 4 }}
data:
  test-transaction.sh: |
    {{- .Values.transaction | nindent 4 }}
