apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "test-transaction.fullname" . }}
  labels:
    {{- include "test-transaction.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "test-transaction.labels" . | nindent 12 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "test-transaction.serviceAccountName" . }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
              args:
                - "{{ .Values.keycloakUrl }}"
                - "{{ .Values.userName }}"
                - "{{ .Values.userPassword }}"
                - http://{{ include "test-transaction.fullname" . }}-gateway
                {{- if .Values.useIPv4 }}
                - "-4"
                {{- end }}
                {{- if .Values.createTestShop }}
                - --create-test-shop
                {{- end }}
          restartPolicy: OnFailure
