apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "test-transaction.fullname" . }}
  labels:
    {{- include "test-transaction.labels" . | nindent 4 }}
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          serviceAccountName: {{ include "test-transaction.serviceAccountName" . }}
          containers:
            - name: gateway
              image: nginx
              ports:
                - containerPort: 80
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/nginx/nginx.conf
                  subPath: nginx.conf
                  readOnly: true
                - name: config-volume
                  mountPath: /etc/nginx/virtualhost/virtualhost.conf
                  subPath: virtualhost.conf
                  readOnly: true
            - name: test_transaction
              image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/test-transaction/test-transaction.sh
                  subPath: test-transaction.sh
                  readOnly: true
              command:
              args:
              - /bin/sh
              - -c
              - /opt/test-transaction/test-transaction.sh
          volumes:
            - name: config-volume
              configMap:
                name: {{ include "test-transaction.fullname" . }}
                items:
                - key: test-transaction.sh
                  path: test-transaction.sh
                  mode: 0755
                - key: nginx.conf
                  path: nginx.conf
                - key: virtualhost.conf
                  path: virtualhost.conf
          restartPolicy: OnFailure
