apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-transaction.fullname" . }}-gateway
  labels:
    {{- include "test-transaction.gwLabels" . | nindent 4 }}
spec:
  type: {{ .Values.gatewayService.type }}
  ports:
    - port: {{ .Values.gatewayService.port }}
      targetPort: 80
      protocol: TCP
      name: api
  selector:
    {{- include "test-transaction.gwSelectorLabels" . | nindent 4 }}
