apiVersion: v1
kind: Service
metadata:
  name: {{ include "shumway.fullname" . }}
  labels:
    {{- include "shumway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.ports.management }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "shumway.selectorLabels" . | nindent 4 }}
