apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cds.fullname" . }}
  labels:
    {{- include "cds.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cds.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        cds/properties-hash: {{ include "cds.propertiesHash" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cds.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: woody
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: woody
          readinessProbe:
            httpGet:
              path: /health
              port: woody
          volumeMounts:
            - name: config-volume
              mountPath: /opt/cds/releases/0.1.0/sys.config
              subPath: sys.config
              readOnly: true
            - name: config-volume
              mountPath: /opt/cds/releases/0.1.0/vm.args
              subPath: vm.args
              readOnly: true
            - name: config-volume
              mountPath: /opt/cds/erl_inetrc
              subPath: erl_inetrc
              readOnly: true
            - name: secret
              mountPath: /var/lib/cds/
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "cds.fullname" . }}
            items:
            - key: sys.config
              path: sys.config
            - key: vm.args
              path: vm.args
            - key: erl_inetrc
              path: erl_inetrc
        - name: secret
          secret:
            secretName: {{ include "cds.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
