controller:
  image:
    repository: dmitryrbk/ptaf4-ingress
    tag: "v4.0.6"
    pullPolicy: IfNotPresent
  serviceAccount:
    imagePullSecrets:
      - name: stanreg
  volumeMounts:
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /auth/.htpasswd
      name: basic
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 512M
      name: dshm
    - name: basic
      secret:
        secretName: basic-auth
  service:
    externalIPs:
      - 10.126.120.135
    externalTrafficPolicy: Cluster
  config:
    entries:
      main-snippets: |
        load_module /opt/ptaf/lib/ngx_wrapper.so;
        env POD_IP=127.0.0.1;
      http-snippets: |
        ptaf_config "tcp://eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJ0b2tlbl9pZCI6IjRhZTk1OWY1LTQ3N2UtNDZkZi05YzI3LTRkYzI1ZjU2ZjgyYiIsInRlbmFudF9pZCI6ImU4YzUxNGU2LWYyYjEtNDg3YS1hOTdjLTZmZjk4YjRlNTAzNCIsInJvbGVzIjpbImNvcmUiLCJ3c2MtYWdlbnQiXX0.TgJedEpfJga_4w2AsmWPCHvtTP7-Vlm76-zbysVTGBh1WIl7OzaSAVciyMXEaW6nNbvCWVpGbyk4-VCjWg9z3Q@172.21.22.237:8443";
