apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy-mocket-inspector.fullname" . }}-api
  labels:
    {{- include "proxy-mocket-inspector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8022
      protocol: TCP
      name: api
  selector:
    {{- include "proxy-mocket-inspector.selectorLabels" . | nindent 4 }}
