replicaCount: 1

ingress:
  host: rbkmoney.standoff.city
  path: /v2/processing/payment-resources
  
metrics:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: prometheus
