replicaCount: 1

ingress:
  host: api.rbkmoney.standoff.city
  path: /v2/processing/payment-resources
metrics:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: prometheus

resources:
  requests:
    cpu: 100m
    memory: 128Mi
