---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "wapi-pcidss-v0.fullname" . }}
  labels:
    {{- include "wapi-pcidss-v0.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ include "wapi-pcidss-v0.fullname" . }}
              servicePort: {{ .Values.service.port }}
{{ if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secret }}
{{- end -}}
