---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wapi-pcidss-v0.fullname" . }}
type: Opaque
data:
  private.pem: {{ .Values.privatePem | b64enc | quote }}
  jwk.json:    {{ .Values.tokenEnctyptionKey1 | b64enc | quote }}
