apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "binbase.fullname" . }}
  labels:
    {{- include "binbase.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "binbase.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "binbase.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        binbase/properties-hash: {{ include "binbase.propertiesHash" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "binbase.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: 8022
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: api
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: api
          volumeMounts:
            - name: config-volume
              mountPath: /opt/binbase/entrypoint.sh
              subPath: entrypoint.sh
              readOnly: true
            - name: config-volume
              mountPath: /opt/hooker/logback.xml
              subPath: logback.xml
              readOnly: true
            - name: config-volume
              mountPath: /opt/hooker/loggers.xml
              subPath: loggers.xml
              readOnly: true
          command: ["/opt/binbase/entrypoint.sh"]
          args:
            - -jar
            - /opt/binbase/binbase.jar
            - --logging.config=/opt/binbase/logback.xml
            - --management.security.enabled=false
            - --spring.batch.job.enabled=false
            - --client.cds.url={{ .Values.cdsUrl }}
            - --spring.flyway.enabled=false
            - --spring.batch.initialize-schema=never
          env:
            - name: LOGBACK_SERVICE_NAME
              value: "binbase"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "binbase.fullname" . }}
            items:
            - key: entrypoint.sh
              path: entrypoint.sh
              mode: 0755
            - key: logback.xml
              path: logback.xml
            - key: loggers.xml
              path: loggers.xml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
