apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
{{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  name:  {{ include "capi-v1.fullname" . }}
  labels:
    {{- include "capi-v1.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ include "capi-v1.fullname" . }}
          servicePort: {{ .Values.service.port }}
{{ if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secret }}
{{- end -}}
