apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elastic.nameref }}
spec:
  version: {{ .Chart.AppVersion }}
  nodeSets:
  - name: default
    count: {{ .Values.elastic.replicas }}
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    podTemplate:
      {{- toYaml .Values.elastic.podTemplate | nindent 6 }}

