{{- if .Values.filebeat.enabled -}}
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
spec:
  type: filebeat
  version: {{ .Chart.AppVersion }}
  elasticsearchRef:
    name: {{ .Values.elastic.nameref }}
  kibanaRef:
    name: {{ .Values.kibana.nameref }}
  config:
    filebeat.autodiscover:
      providers:
      - type: kubernetes
        hints.enabled: true
        default_config.enabled: false
        node: ${NODE_NAME}
    logging:
      level: error
    output.elasticsearch:
      index: "filebeat-rbkmoney-processing-%{[agent.version]}-%{+yyyy.MM.dd}"
    setup:
      ilm.enabled: false
      dashboards:
        enabled: false
        index: filebeat-rbkmoney-processing-*
      template:
        enabled: true
        overwrite: true
        pattern: filebeat-rbkmoney-processing-*
        name: filebeat-rbkmoney-processing
        json:
          enabled: true
          path: "/etc/template.json"
          name: filebeat-rbkmoney-processing
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          - name: index-template
            mountPath: /etc/template.json
            subPath: template.json
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: index-template
          configMap:
            name: filebeat-index-template
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: default
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
