replicaCount: 1

ingress:
  host: api.rbkmoney.standoff.city
  path: /v1/processing/payment-resources
metrics:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: prometheus
