agent:
  policyEnforcementMode: "never"
global:
  #ipv6:
  #  enabled: true
  hubble:
    enabled: true
    #ui:
    #  enabled: true
    #relay:
    #  enabled: true
    #listenAddress: ":4244"
#hubble-relay:
#  enabled: true
#  listenPort: "4245"
