apiVersion: v1
kind: Service
metadata:
  name: {{ include "capi-v2.fullname" . }}
  labels:
    {{- include "capi-v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: api
  selector:
    {{- include "capi-v2.selectorLabels" . | nindent 4 }}
